Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7"
  config.vm.define "centos7"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "centos7"
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install httpd -y
  SHELL
end
