Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = "centos7"
  config.vm.define "centos7"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "centos7"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    yum clean all
    yum update -y
    yum install httpd -y
  SHELL
end
